---
sidebar: sidebar 
permalink: reference_infrastructure_as_code.html 
keywords: ansible, playbook, automation 
summary: Los equipos de DevOps utilizan diversas herramientas para automatizar la configuración de nuevos entornos, lo que les permite tratar la infraestructura como código. Dos de estas herramientas son Ansible y Terraform. Hemos desarrollado muestras de Ansible y Terraform que el equipo de DevOps puede usar con Cloud Manager para automatizar e integrar Cloud Volumes ONTAP con la infraestructura como código. 
---
= Muestras de automatización para la infraestructura como código
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilice los recursos de esta página para obtener ayuda para la integración Cloud Manager y Cloud Volumes ONTAP con su https://["infraestructura como código"^].

Los equipos de DevOps utilizan diversas herramientas para automatizar la configuración de nuevos entornos, lo que les permite tratar la infraestructura como código. Dos de estas herramientas son Ansible y Terraform. Hemos desarrollado muestras de Ansible y Terraform que el equipo de DevOps puede usar con Cloud Manager para automatizar e integrar Cloud Volumes ONTAP con la infraestructura como código.

https://["Vea las muestras de automatización"^].

Por ejemplo, puede usar libros de estrategia de Ansible de muestra para poner en marcha Cloud Manager y Cloud Volumes ONTAP, crear un agregado y crear un volumen. Modifique las muestras para su entorno o cree nuevos libros de estrategia basados en las muestras.

*Enlaces relacionados*

* https://["Blog de cloud de NetApp: Uso de API DE REST de Cloud Manager con acceso federado"^]
* https://["Blog sobre cloud de NetApp: Automatización cloud con Cloud Volumes ONTAP Y REST"^]
* https://["Blog sobre cloud de NetApp: Clonado de datos automatizado para pruebas de aplicaciones de software basadas en cloud"^]
* https://["Blog de NetApp: Infrastructure-as-Code (IAC) Accelerated with Ansible + NetApp"^]
* https://["ThePub de NetApp: Gestión de configuraciones y automatización con Ansible"^]
* https://["ThePub de NetApp: Roles para el uso de Ansible ONTAP"^]

