---
sidebar: sidebar 
permalink: reference_additional_info.html 
keywords: community, forums, help, support, videos, policies, json, api, ontap, release notes, bugs, limitations, known issues, permissions, apis 
summary: Puede obtener ayuda y encontrar más información sobre Cloud Manager y Cloud Volumes ONTAP a través de diversos recursos, como vídeos, foros y soporte. 
---
= Dónde encontrar ayuda y más información
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede obtener ayuda y encontrar más información sobre Cloud Manager y Cloud Volumes ONTAP a través de diversos recursos, como vídeos, foros y soporte.

* https://["Vídeos para Cloud Manager y Cloud Volumes ONTAP"^]
+
Vea vídeos que le muestran cómo poner en marcha y gestionar Cloud Volumes ONTAP en AWS y Azure, y cómo replicar datos en su cloud híbrido.

* http://["Políticas para Cloud Manager"^]
+
Descargue los archivos JSON que incluyen los permisos que Cloud Manager necesita para realizar acciones en AWS y Azure.

* link:api.html["Guía para desarrolladores de API de Cloud Manager"^]
+
Lea una descripción general de las API, ejemplos de cómo utilizarlas y una referencia de API.

* Formación para Cloud Volumes ONTAP
+
** https://["Principios básicos de Cloud Volumes ONTAP"^]
** https://["Implementación y gestión de Cloud Volumes ONTAP para Azure"^]


* Informes técnicos
+
** https://["Informe técnico de NetApp 4383: Caracterización del rendimiento de Cloud Volumes ONTAP en Amazon Web Services con cargas de trabajo de las aplicaciones"^]
** https://["Informe técnico de NetApp 4671: Caracterización del rendimiento de Cloud Volumes ONTAP en Azure con cargas de trabajo de aplicaciones"^]


* https://["Guía exprés de preparación para la recuperación de desastres de SVM de Cloud Volumes ONTAP 9"^]
+
Describe cómo configurar rápidamente una SVM de destino con el fin de prepararse para la recuperación de desastres.

* https://["Guía exprés de recuperación de desastres de SVM de Cloud Volumes ONTAP 9"^]
+
Describe cómo activar rápidamente una SVM de destino después de un desastre y, a continuación, reactivar la SVM de origen.

* http://["Centro de documentación de ONTAP 9"^]
+
Acceda a documentación de productos para ONTAP, que puede ayudarle cuando utilice Cloud Volumes ONTAP.

* https://["Soporte Cloud Volumes ONTAP de NetApp"^]
+
Acceda a recursos de soporte para obtener ayuda y solucionar problemas con Cloud Volumes ONTAP.

* https://["Comunidad de NetApp: Servicios de datos en el cloud"^]
+
Conéctese con colegas, realice preguntas, intercambie ideas, encuentre recursos y comparta prácticas recomendadas.

* http://["Cloud Central de NetApp"^]
+
Encuentre información sobre otros productos y soluciones de NetApp para el cloud.

* http://["Documentación de productos de NetApp"^]
+
Busque en la documentación de productos de NetApp instrucciones, recursos y respuestas.


