---
sidebar: sidebar 
permalink: task_enabling_flash_cache.html 
keywords: cloud volumes ontap, aws, ec2, flash cache, read-intensive, read, random, databases, email, file services, c5d.4xlarge, c5d.9xlarge, r5d.2xlarge, compression, performance 
summary: Algunos tipos de instancias de EC2 incluyen almacenamiento NVMe local, que Cloud Volumes ONTAP utiliza como Flash Cache. Flash Cache acelera el acceso a los datos mediante el almacenamiento en caché inteligente en tiempo real de datos recientes de usuarios y metadatos de NetApp. Es efectivo para cargas de trabajo de lectura intensiva aleatoria, como bases de datos, correo electrónico y servicios de archivos. 
---
= Habilitación de Flash Cache en Cloud Volumes ONTAP en AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Algunos tipos de instancias de EC2 incluyen almacenamiento NVMe local, que Cloud Volumes ONTAP utiliza como _Flash Cache_. Flash Cache acelera el acceso a los datos mediante el almacenamiento en caché inteligente en tiempo real de datos recientes de usuarios y metadatos de NetApp. Es efectivo para cargas de trabajo de lectura intensiva aleatoria, como bases de datos, correo electrónico y servicios de archivos.


NOTE: Cloud Volumes ONTAP no admite el recalentamiento de la caché después de un reinicio.

.Pasos
. Seleccione uno de los siguientes tipos de instancia de EC2, disponibles con las licencias Premium y BYOL:
+
** c5d.4 x grande
** c5d.9xlarge
** r5d.2xgrande


. Deshabilite la compresión en todos los volúmenes.
+
La compresión debe deshabilitarse en todos los volúmenes para aprovechar las mejoras de rendimiento de Flash Cache. No puede seleccionar eficiencia de almacenamiento al crear un volumen desde Cloud Manager o puede crear un volumen y, a continuación, hacerlo http://["Deshabilite la compresión de datos mediante la CLI"^].


